language: c++

notifications:
  email: false

branches:
  only:
    - master

compiler: clang

env:
  - MODULES=Off CXX_COMPILER=clang++-5.0 COMPILER=clang-5.0 CMS=Off
  - MODULES=print CXX_COMPILER=clang++-5.0 COMPILER=clang-5.0 CMS=Off
  - MODULES=Off CXX_COMPILER=clang++-5.0 COMPILER=clang-5.0 CMS=On
  - MODULES=print CXX_COMPILER=clang++-5.0 COMPILER=clang-5.0 CMS=On

dist: trusty
sudo: enable
python: '3.3'
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
    packages: ['clang-5.0', 'g++-7']
script:
  - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES $CMS
