language: cpp

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0', 'ppa:jonathonf/gcc-7.1']
          packages: ['clang-5.0', 'g++-7', 'gcc-7']
      env:
        - MODULES=On
        - CXX_COMPILER=clang++-5.0
        - COMPILER=clang-5.0

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0', 'ppa:jonathonf/gcc-7.1']
          packages: ['clang-5.0', 'g++-7', 'gcc-7']
      env:
        - MODULES=Off
        - CXX_COMPILER=clang++-5.0
        - COMPILER=clang-5.0

script:
  - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES
