sudo: required

branches:
  only:
    - master

language: c++

compiler:
  - gcc
  - clang

notifications:
  email: false

arch:
  packages:
    - cmake
    - clang
    - clang-tools-extra
    - llvm-libs
    - llvm
    - valgrind
  - env:
    - MODULES=On
    - CXX_COMPILER=clang++-5.0
    - COMPILER=clang-5.0
  - env:
    - MODULES=Off
    - CXX_COMPILER=clang++-5.0
    - COMPILER=clang-5.0
  script:
    - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
