language: cpp, python

notifications:
  email: false

branches:
  only:
    - master

python:
  - "3.6"

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      python:
        - "3.6"
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0', 'deadsnakes']
          packages: ['clang-5.0', 'g++-7', 'python3.6']
      env:
        - MODULES=On
        - CXX_COMPILER=clang++-5.0
        - COMPILER=clang-5.0

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']
      env:
        - MODULES=Off
        - CXX_COMPILER=clang++-5.0
        - COMPILER=clang-5.0

script:
  - pytest
  - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES
