language: cpp

notifications:
  email: false

branches:
  only:
    - master

env:
  - MODULES=On CXX_COMPILER=clang++ COMPILER=clang
  - MODULES=Off CXX_COMPILER=clang++ COMPILER=clang

compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      python: '3.3'
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']
      script:
        - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES

    - os: linux
      sudo: required
      script:
        - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES
      before_install:
        - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

arch:
  packages:
    - cmake
    - clang
    - clang-tools-extra
    - llvm-libs
    - llvm
    - python
    - python3
  script:
    - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES
