language: cpp, python

notifications:
  email: false

branches:
  only:
    - master

sudo: required

env:
  - MODULES=On CXX_COMPILER=clang++ COMPILER=clang
  - MODULES=Off CXX_COMPILER=clang++ COMPILER=clang

compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      python: '3.3'
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0', 'g++-7']

    - os: linux
	  arch:
	    packages:
		  - cmake
	  	  - clang
		  - clang-tools-extra
		  - llvm-libs
		  - llvm
		  - python
		  - python3

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
  - ./scripts/run_travis.sh $COMPILER $CXX_COMPILER $MODULES
